### ISSUE TITLE
... gap in config

### ISSUE THREAD

**Issue by carlos-dubon** [Angel-Ponce/any-pagination#1]
I want to customize the gap between items

1 ... 5 6 7 ... 99
1 2 3 ... 20 21 22 ... 56 57 58
1 2 ... 5 6 7 ... 98 99

**Comment by Angel-Ponce** [comment]
Are you willing to contribuite ?

**Comment by Angel-Ponce** [comment]
I'll resume this project, so, could you express with more precision whats your requirement?
I understand that you need to cutomize the `gap`/`space` between corners of pagination??
Or do you need also to customize the `siblings` of the current page?

**Comment by carlos-dubon** [comment]
both

**Comment by Angel-Ponce** [comment]
@carlos-dubon 
Now `v1.2.0` package supports:

```typescript
{
   siblingCount: number;
   boundaryCount: number;
}
```

to configure gap in your pagination components!! 🚀
let me know if this fix your problem?

**Comment by Angel-Ponce** [comment]
I'll asume that it was fixed for you
